const countedHeader = {
  A: "No",
  B: "Nama Produk",
  C: "Kode Produk",
  D: "Tanggal Pembelian",
  E: "Harga Produk",
  F: "Harga Produk DPP",
  G: "Jumlah Pembelian",
  H: "Diskon",
  I: "Total Pembayaran",
  J: "Total DPP",
  K: "Total PPN",
};

const orderedHeader = {
  A: "No",
  B: "Nama Pembeli",
  C: "Nama Produk",
  D: "Kode Produk",
  E: "Tanggal Pembelian",
  F: "Harga Produk",
  G: "Harga Produk DPP",
  H: "Jumlah Pembelian",
  I: "Diskon",
  J: "Total Pembayaran",
  K: "Total DPP",
  L: "Total PPN",
  M: "Faktur",
};

const totalTransactionHeader = {
  A: "No",
  B: "Nama Pembeli",
  C: "Jumlah Pembelian",
  D: "Jumlah Diskon",
  E: "Total Pembayaran",
  F: "Total DPP",
  G: "Total PPN",
  H: "Faktur",
};

const reportHeader = {
  A: "Nama Pelanggan",
  B: "NPWP",
  C: "Kode Faktur",
  D: "Status Faktur",
  E: "Nomor Faktur",
  F: "Masa",
  G: "Tahun",
  H: "Tanggal",
  I: "Total DPP",
  J: "Total PPN",
  K: "Total Bayar",
};

const importHeader = [
  {
    A: "FK",
    B: "KD_JENIS_TRANSAKSI",
    C: "FG_PENGGANTI",
    D: "NOMOR_FAKTUR",
    E: "MASA_PAJAK",
    F: "TAHUN_PAJAK",
    G: "TANGGAL_FAKTUR",
    H: "NPWP",
    I: "NAMA",
    J: "ALAMAT_LENGKAP",
    K: "JUMLAH_DPP",
    L: "JUMLAH_PPN",
    M: "JUMLAH_PPNBM",
    N: "ID_KETERANGAN_TAMBAHAN",
    O: "FG_UANG_MUKA",
    P: "UANG_MUKA_DPP",
    Q: "UANG_MUKA_PPN",
    R: "UANG_MUKA_PPNBM",
    S: "REFERENSI",
    T: "KODE_DOKUMEN_PENDUKUNG",
  },
  {
    A: "LT",
    B: "NPWP",
    C: "NAMA",
    D: "JALAN",
    E: "BLOK",
    F: "NOMOR",
    G: "RT",
    H: "RW",
    I: "KECAMATAN",
    J: "KELURAHAN",
    K: "KABUPATEN",
    L: "PROPINSI",
    M: "KODE_POS",
    N: "NOMOR_TELEPON",
  },
  {
    A: "OF",
    B: "KODE_OBJEK",
    C: "NAMA",
    D: "HARGA_SATUAN",
    E: "JUMLAH_BARANG",
    F: "HARGA_TOTAL",
    G: "DISKON",
    H: "DPP",
    I: "PPN",
    J: "TARIF_PPNBM",
    K: "PPNBM",
  },
];

export const Constants = {
  outputFile: {
    counted: "Counted Clients.xlsx",
    ordered: "Ordered Clients.xlsx",
    totalTransaction: "Total Transactions.xlsx",
    import: "import.xlsx",
    report: "report",
  },
  excelHeader: {
    counted: countedHeader,
    ordered: orderedHeader,
    totalTransaction: totalTransactionHeader,
    report: reportHeader,
    import: importHeader,
  },
};
